steps:
- name: 'gcr.io/cloud-builders/docker'
  args: 
  - build
  - -t
  - gcr.io/$PROJECT_ID/fluentd:$BRANCH_NAME
  - .
- name: 'gcr.io/cloud-builders/docker'
  args:
  - push
  - gcr.io/$PROJECT_ID/fluentd:$BRANCH_NAME
- name: 'gcr.io/cloud-builders/docker'
  args:
  - tag
  - gcr.io/$PROJECT_ID/fluentd:$BRANCH_NAME
  - gcr.io/$PROJECT_ID/fluentd:$COMMIT_SHA
- name: 'gcr.io/cloud-builders/kubectl'
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    [[ "$BRANCH_NAME" != "master" ]] && /builder/kubectl.bash set image deployments -l role=fluentd-nats fluentd=gcr.io/$PROJECT_ID/fluentd:$BRANCH_NAME --record || echo "skipping . . ."
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=heili-us-central1'
images:
- 'gcr.io/$PROJECT_ID/fluentd:$COMMIT_SHA'
- 'gcr.io/$PROJECT_ID/fluentd:$BRANCH_NAME'
